import type { Metadata, Viewport } from "next";
import { Bangers, Comic_Neue, Space_Mono } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";

import Footer from "@/components/Footer";
import { MobileUtilitiesFAB } from "@/components/MobileUtilitiesFAB";
import { Navigation } from "@/components/Navigation";
import { PWAInstallPrompt } from "@/components/PWAInstallPrompt";
import { PostHogProvider } from "@/components/PostHogProvider";
import { Providers } from "@/components/Providers";
import { ServiceWorkerProvider } from "@/components/ServiceWorkerProvider";

import "./globals.css";

// Pop Art / Lichtenstein Typography
const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bangers",
  display: "swap",
});

const comicNeue = Comic_Neue({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-comic-neue",
  display: "swap",
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-space-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Collectors Chest - Track, Value & Trade Your Comics",
  description:
    "Scan comics. Track value. Collect smarter. Collectors Chest is the all-in-one platform that helps comic collectors discover value, organize with pride, and buy, sell, and trade with confidence.",
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/favicon.png", type: "image/png", sizes: "32x32" },
      { url: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512x512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Collectors Chest",
  },
  other: {
    "mobile-web-app-capable": "yes",
  },
};

// iOS PWA splash images. iOS Safari ignores manifest.json's background_color
// for the splash screen — it requires per-device apple-touch-startup-image
// links matching exact viewport dimensions. Without these, iOS shows a blank
// white/black screen until the app boots.
//
// Each entry pairs a media query (matching device pixel dimensions + DPR) with
// the matching pre-rendered splash bitmap. Generated by
// scripts/generate-splash-assets.ts from the Figma source.
const APPLE_SPLASH_LINKS: Array<{ media: string; href: string }> = [
  // iPhone 12/13/14 Pro Max (1284x2778 @3x)
  {
    media:
      "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)",
    href: "/icons/apple-splash-1284-2778.png",
  },
  // iPhone 12/13/14 standard (1170x2532 @3x)
  {
    media:
      "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)",
    href: "/icons/apple-splash-1170-2532.png",
  },
  // iPhone XR/11 (828x1792 @2x)
  {
    media:
      "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)",
    href: "/icons/apple-splash-828-1792.png",
  },
  // iPhone X/XS/11 Pro (1125x2436 @3x)
  {
    media:
      "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)",
    href: "/icons/apple-splash-1125-2436.png",
  },
  // iPhone 6/7/8 (750x1334 @2x)
  {
    media:
      "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)",
    href: "/icons/apple-splash-750-1334.png",
  },
];

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: "#FFF200", // Pop Art Yellow
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          {APPLE_SPLASH_LINKS.map((link) => (
            <link
              key={link.href}
              rel="apple-touch-startup-image"
              media={link.media}
              href={link.href}
            />
          ))}
        </head>
        <body
          className={`${bangers.variable} ${comicNeue.variable} ${spaceMono.variable} font-body`}
        >
          <PostHogProvider>
            <ServiceWorkerProvider>
              <Providers>
                <div className="min-h-screen bg-pop-cream pb-20 md:pb-0">
                  <Navigation />
                  <main className="container mx-auto px-4 py-8">{children}</main>
                  <div className="container mx-auto px-4">
                    <Footer />
                  </div>
                  <MobileUtilitiesFAB />
                  <PWAInstallPrompt />
                </div>
              </Providers>
            </ServiceWorkerProvider>
          </PostHogProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
