"use client";

import { useState } from "react";
import { Brain, X, ChevronDown, ChevronUp } from "lucide-react";

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: "How do I add a comic to my collection?",
    answer:
      "Click 'Scan a Book' on the home page. You can either upload a photo of the cover for AI recognition, scan a barcode, or enter details manually. After reviewing the details, click 'Add to Collection'.",
  },
  {
    question: "What features are available for guests vs registered users?",
    answer:
      "Guests can explore the app, view the 'How It Works' guide, check out Professor's Hottest Books, and try scanning a comic. However, to save comics to your collection, track values, create custom lists, mark items as sold, and access your data across devices, you'll need to create a free account. Registration unlocks the full collector experience!",
  },
  {
    question: "What does 'Slabbed' mean?",
    answer:
      "A 'slabbed' comic is one that has been professionally graded by a service like CGC, CBCS, or PGX. The comic is sealed in a protective case with a grade label. When you check 'Professionally Graded (Slabbed)', your comic is automatically added to the Slabbed list.",
  },
  {
    question: "How accurate are the price estimates?",
    answer:
      "Price estimates are generated by AI based on recent market trends. They provide a general guideline but actual prices can vary based on condition, demand, and where you sell. For the most accurate values, check recent eBay sold listings.",
  },
  {
    question: "Can I create custom lists?",
    answer:
      "Yes! Go to your Collection page and look for the option to create a new list. You can organize comics by series, favorites, want list, or any category you choose.",
  },
  {
    question: "How do I mark a comic as sold?",
    answer:
      "View the comic in your collection and look for the 'Mark as Sold' option. Enter the sale price and date, and it will be moved to your sales history for profit/loss tracking.",
  },
  {
    question: "What is the 'Professor's Hottest Books' feature?",
    answer:
      "This is a weekly market analysis showing the top 10 comics currently in high demand. It includes key facts about each book, why it's hot (movie announcements, speculation, etc.), and current price ranges.",
  },
  {
    question: "How do I edit a comic's details?",
    answer:
      "Click on any comic in your collection to view its details. Look for the 'Edit Details' button to modify information like grade, purchase price, or notes.",
  },
  {
    question: "What grades should I use for my comics?",
    answer:
      "Use standard comic grading terms: NM (Near Mint), VF (Very Fine), FN (Fine), VG (Very Good), G (Good), FR (Fair), PR (Poor). For slabbed comics, use the numeric grade from the certification label (e.g., 9.8, 9.6).",
  },
];

export default function AskProfessor() {
  const [isOpen, setIsOpen] = useState(false);
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  return (
    <>
      {/* Floating Button */}
      <button
        onClick={() => setIsOpen(true)}
        className="fixed bottom-6 right-6 z-40 group"
        aria-label="Ask the Professor"
      >
        <div className="relative">
          {/* Glow effect */}
          <div className="absolute inset-0 bg-yellow-400 rounded-full blur-md opacity-50 group-hover:opacity-75 transition-opacity animate-pulse" />
          {/* Button */}
          <div className="relative w-14 h-14 bg-gradient-to-br from-blue-700 to-blue-900 rounded-full flex items-center justify-center shadow-lg hover:shadow-xl transition-all hover:scale-105 ring-2 ring-yellow-400">
            <Brain className="w-7 h-7 text-yellow-400" />
          </div>
          {/* Floating ring animation */}
          <div className="absolute inset-0 rounded-full border-2 border-yellow-400 animate-ping opacity-20" />
        </div>
        {/* Tooltip */}
        <span className="absolute bottom-full right-0 mb-2 px-3 py-1 bg-blue-900 text-yellow-400 text-sm rounded-lg opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap font-medium">
          Ask the Professor
        </span>
      </button>

      {/* Modal Overlay */}
      {isOpen && (
        <div
          className="fixed inset-0 z-50 bg-black/50 flex items-end sm:items-center justify-center p-4"
          onClick={() => setIsOpen(false)}
        >
          {/* Modal Content */}
          <div
            className="bg-white rounded-t-2xl sm:rounded-2xl w-full max-w-lg max-h-[80vh] overflow-hidden shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="bg-gradient-to-r from-blue-700 to-blue-900 p-6 text-white">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-yellow-400/20 rounded-xl">
                    <Brain className="w-6 h-6 text-yellow-400" />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-yellow-400">Ask the Professor</h2>
                    <p className="text-blue-200 text-sm">
                      Your guide to Collector&apos;s Catalog
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => setIsOpen(false)}
                  className="p-2 hover:bg-yellow-400/20 rounded-lg transition-colors"
                >
                  <X className="w-5 h-5 text-yellow-400" />
                </button>
              </div>
            </div>

            {/* FAQ List */}
            <div className="overflow-y-auto max-h-[calc(80vh-120px)] p-4">
              <p className="text-gray-600 text-sm mb-4">
                Welcome, collector! Here are answers to commonly asked questions.
                Can&apos;t find what you need? We&apos;re always adding more.
              </p>
              <div className="space-y-2">
                {faqs.map((faq, index) => (
                  <div
                    key={index}
                    className="border border-gray-200 rounded-lg overflow-hidden"
                  >
                    <button
                      onClick={() => toggleFAQ(index)}
                      className="w-full flex items-center justify-between p-4 text-left hover:bg-gray-50 transition-colors"
                    >
                      <span className="font-medium text-gray-900 pr-4">
                        {faq.question}
                      </span>
                      {expandedIndex === index ? (
                        <ChevronUp className="w-5 h-5 text-gray-500 flex-shrink-0" />
                      ) : (
                        <ChevronDown className="w-5 h-5 text-gray-500 flex-shrink-0" />
                      )}
                    </button>
                    {expandedIndex === index && (
                      <div className="px-4 pb-4 text-gray-600 text-sm border-t border-gray-100 pt-3">
                        {faq.answer}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
