-- =============================================
-- Seed key_comics table with curated data
-- 402 entries from keyComicsDatabase.ts
-- =============================================

INSERT INTO key_comics (title, issue_number, publisher, key_info, source) VALUES
-- MARVEL - SPIDER-MAN
('Amazing Fantasy', '15', 'Marvel', ARRAY['First appearance of Spider-Man', 'First appearance of Uncle Ben', 'First appearance of Aunt May'], 'curated'),
('Amazing Spider-Man', '1', 'Marvel', ARRAY['First issue of Amazing Spider-Man series', 'First appearance of J. Jonah Jameson', 'First appearance of Chameleon'], 'curated'),
('Amazing Spider-Man', '2', 'Marvel', ARRAY['First appearance of the Vulture'], 'curated'),
('Amazing Spider-Man', '3', 'Marvel', ARRAY['First appearance of Doctor Octopus'], 'curated'),
('Amazing Spider-Man', '4', 'Marvel', ARRAY['First appearance of Sandman', 'First appearance of Betty Brant'], 'curated'),
('Amazing Spider-Man', '6', 'Marvel', ARRAY['First appearance of the Lizard'], 'curated'),
('Amazing Spider-Man', '9', 'Marvel', ARRAY['First appearance of Electro'], 'curated'),
('Amazing Spider-Man', '13', 'Marvel', ARRAY['First appearance of Mysterio'], 'curated'),
('Amazing Spider-Man', '14', 'Marvel', ARRAY['First appearance of the Green Goblin'], 'curated'),
('Amazing Spider-Man', '20', 'Marvel', ARRAY['First appearance of Scorpion'], 'curated'),
('Amazing Spider-Man', '25', 'Marvel', ARRAY['First cameo appearance of Mary Jane Watson'], 'curated'),
('Amazing Spider-Man', '28', 'Marvel', ARRAY['First Molten Man'], 'curated'),
('Amazing Spider-Man', '31', 'Marvel', ARRAY['First appearance of Gwen Stacy', 'First appearance of Harry Osborn'], 'curated'),
('Amazing Spider-Man', '42', 'Marvel', ARRAY['First full appearance of Mary Jane Watson'], 'curated'),
('Amazing Spider-Man', '50', 'Marvel', ARRAY['First appearance of Kingpin', 'Classic Spider-Man No More cover'], 'curated'),
('Amazing Spider-Man', '101', 'Marvel', ARRAY['First appearance of Morbius the Living Vampire'], 'curated'),
('Amazing Spider-Man', '121', 'Marvel', ARRAY['Death of Gwen Stacy'], 'curated'),
('Amazing Spider-Man', '122', 'Marvel', ARRAY['Death of the Green Goblin (Norman Osborn)'], 'curated'),
('Amazing Spider-Man', '129', 'Marvel', ARRAY['First appearance of the Punisher', 'First appearance of the Jackal'], 'curated'),
('Amazing Spider-Man', '194', 'Marvel', ARRAY['First appearance of Black Cat'], 'curated'),
('Amazing Spider-Man', '238', 'Marvel', ARRAY['First appearance of Hobgoblin'], 'curated'),
('Amazing Spider-Man', '252', 'Marvel', ARRAY['First appearance of Spider-Man black costume in main continuity'], 'curated'),
('Amazing Spider-Man', '298', 'Marvel', ARRAY['First Todd McFarlane art on Amazing Spider-Man', 'First cameo of Eddie Brock'], 'curated'),
('Amazing Spider-Man', '299', 'Marvel', ARRAY['First cameo appearance of Venom'], 'curated'),
('Amazing Spider-Man', '300', 'Marvel', ARRAY['First full appearance of Venom', 'Origin of Venom'], 'curated'),
('Amazing Spider-Man', '316', 'Marvel', ARRAY['First Venom cover'], 'curated'),
('Amazing Spider-Man', '344', 'Marvel', ARRAY['First appearance of Cletus Kasady'], 'curated'),
('Amazing Spider-Man', '361', 'Marvel', ARRAY['First full appearance of Carnage'], 'curated'),
('Amazing Spider-Man', '569', 'Marvel', ARRAY['First appearance of Anti-Venom'], 'curated'),
('Amazing Spider-Man', '654', 'Marvel', ARRAY['First appearance of Agent Venom (Flash Thompson)'], 'curated'),
('Amazing Spider-Man', '667', 'Marvel', ARRAY['First Spider-Island'], 'curated'),
('Amazing Spider-Man', '700', 'Marvel', ARRAY['Death of Peter Parker', 'Doctor Octopus becomes Spider-Man'], 'curated'),

-- MARVEL - SECRET WARS
('Secret Wars', '1', 'Marvel', ARRAY['First issue of Marvel Super Heroes Secret Wars', 'Major Marvel crossover event begins'], 'curated'),
('Secret Wars', '8', 'Marvel', ARRAY['First appearance of Spider-Man black symbiote costume', 'Origin of the symbiote that becomes Venom'], 'curated'),
('Marvel Super Heroes Secret Wars', '1', 'Marvel', ARRAY['First issue of Marvel Super Heroes Secret Wars', 'Major Marvel crossover event begins'], 'curated'),
('Marvel Super Heroes Secret Wars', '8', 'Marvel', ARRAY['First appearance of Spider-Man black symbiote costume', 'Origin of the symbiote that becomes Venom'], 'curated'),
('Marvel Super-Heroes Secret Wars', '1', 'Marvel', ARRAY['First issue of Marvel Super Heroes Secret Wars', 'Major Marvel crossover event begins'], 'curated'),
('Marvel Super-Heroes Secret Wars', '8', 'Marvel', ARRAY['First appearance of Spider-Man black symbiote costume', 'Origin of the symbiote that becomes Venom'], 'curated'),

-- MARVEL - X-MEN
('X-Men', '1', 'Marvel', ARRAY['First appearance of the X-Men', 'First appearance of Professor X', 'First appearance of Magneto', 'First appearance of Cyclops, Marvel Girl, Beast, Angel, Iceman'], 'curated'),
('X-Men', '4', 'Marvel', ARRAY['First appearance of Scarlet Witch', 'First appearance of Quicksilver', 'First appearance of Brotherhood of Evil Mutants'], 'curated'),
('X-Men', '12', 'Marvel', ARRAY['First appearance of Juggernaut'], 'curated'),
('X-Men', '14', 'Marvel', ARRAY['First appearance of the Sentinels'], 'curated'),
('X-Men', '28', 'Marvel', ARRAY['First Banshee'], 'curated'),
('X-Men', '94', 'Marvel', ARRAY['New X-Men team begins (Wolverine, Storm, Colossus, Nightcrawler join)'], 'curated'),
('X-Men', '101', 'Marvel', ARRAY['First appearance of Phoenix'], 'curated'),
('X-Men', '120', 'Marvel', ARRAY['First cameo of Alpha Flight'], 'curated'),
('X-Men', '121', 'Marvel', ARRAY['First full appearance of Alpha Flight'], 'curated'),
('X-Men', '129', 'Marvel', ARRAY['First appearance of Kitty Pryde', 'First appearance of Emma Frost'], 'curated'),
('X-Men', '130', 'Marvel', ARRAY['First appearance of Dazzler'], 'curated'),
('X-Men', '131', 'Marvel', ARRAY['First White Queen cover'], 'curated'),
('X-Men', '132', 'Marvel', ARRAY['First Hellfire Club'], 'curated'),
('X-Men', '133', 'Marvel', ARRAY['Classic Wolverine cover'], 'curated'),
('X-Men', '135', 'Marvel', ARRAY['Dark Phoenix Saga'], 'curated'),
('X-Men', '137', 'Marvel', ARRAY['Death of Phoenix (Jean Grey)'], 'curated'),
('X-Men', '141', 'Marvel', ARRAY['Days of Future Past begins', 'First Rachel Summers'], 'curated'),
('X-Men', '142', 'Marvel', ARRAY['Days of Future Past concludes'], 'curated'),
('X-Men', '168', 'Marvel', ARRAY['First Madelyne Pryor'], 'curated'),
('X-Men', '221', 'Marvel', ARRAY['First appearance of Mister Sinister'], 'curated'),
('X-Men', '244', 'Marvel', ARRAY['First appearance of Jubilee'], 'curated'),
('X-Men', '266', 'Marvel', ARRAY['First full appearance of Gambit'], 'curated'),
('Uncanny X-Men', '94', 'Marvel', ARRAY['New X-Men team begins (Wolverine, Storm, Colossus, Nightcrawler join)'], 'curated'),
('Uncanny X-Men', '101', 'Marvel', ARRAY['First appearance of Phoenix'], 'curated'),
('Uncanny X-Men', '129', 'Marvel', ARRAY['First appearance of Kitty Pryde', 'First appearance of Emma Frost'], 'curated'),
('Uncanny X-Men', '141', 'Marvel', ARRAY['Days of Future Past begins'], 'curated'),
('Uncanny X-Men', '266', 'Marvel', ARRAY['First full appearance of Gambit'], 'curated'),
('Uncanny X-Men', '282', 'Marvel', ARRAY['First appearance of Bishop'], 'curated'),
('Giant-Size X-Men', '1', 'Marvel', ARRAY['First appearance of the new X-Men team', 'First appearance of Storm', 'First appearance of Colossus', 'First appearance of Nightcrawler', 'Second appearance of Wolverine'], 'curated'),

-- MARVEL - WOLVERINE / HULK
('Incredible Hulk', '1', 'Marvel', ARRAY['First appearance of the Hulk', 'First appearance of Bruce Banner'], 'curated'),
('Incredible Hulk', '180', 'Marvel', ARRAY['First cameo appearance of Wolverine'], 'curated'),
('Incredible Hulk', '181', 'Marvel', ARRAY['First full appearance of Wolverine'], 'curated'),
('Incredible Hulk', '182', 'Marvel', ARRAY['Third appearance of Wolverine'], 'curated'),
('Incredible Hulk', '271', 'Marvel', ARRAY['First comic appearance of Rocket Raccoon'], 'curated'),
('Incredible Hulk', '340', 'Marvel', ARRAY['Classic Todd McFarlane Wolverine vs Hulk cover'], 'curated'),
('Incredible Hulk', '377', 'Marvel', ARRAY['Professor Hulk'], 'curated'),
('Incredible Hulk', '449', 'Marvel', ARRAY['First Thunderbolts'], 'curated'),
('Wolverine', '1', 'Marvel', ARRAY['First Wolverine limited series', 'Frank Miller art'], 'curated'),
('Wolverine', '10', 'Marvel', ARRAY['Classic Sabretooth battle'], 'curated'),
('Wolverine', '66', 'Marvel', ARRAY['Old Man Logan storyline begins'], 'curated'),
('Immortal Hulk', '1', 'Marvel', ARRAY['First Immortal Hulk'], 'curated'),
('Savage She-Hulk', '1', 'Marvel', ARRAY['First She-Hulk'], 'curated'),

-- MARVEL - NEW MUTANTS / DEADPOOL / X-FORCE
('New Mutants', '1', 'Marvel', ARRAY['First appearance of the New Mutants team'], 'curated'),
('New Mutants', '87', 'Marvel', ARRAY['First appearance of Cable'], 'curated'),
('New Mutants', '98', 'Marvel', ARRAY['First appearance of Deadpool', 'First appearance of Domino'], 'curated'),
('New Mutants', '100', 'Marvel', ARRAY['First appearance of X-Force'], 'curated'),
('X-Force', '1', 'Marvel', ARRAY['X-Force begins'], 'curated'),
('X-Force', '2', 'Marvel', ARRAY['Second Deadpool'], 'curated'),
('X-Factor', '6', 'Marvel', ARRAY['First Apocalypse'], 'curated'),
('X-Factor', '24', 'Marvel', ARRAY['First Archangel'], 'curated'),
('Alpha Flight', '1', 'Marvel', ARRAY['First Alpha Flight solo'], 'curated'),
('Alpha Flight', '33', 'Marvel', ARRAY['First Lady Deathstrike'], 'curated'),

-- MARVEL - AVENGERS
('Avengers', '1', 'Marvel', ARRAY['First appearance of the Avengers team', 'First Avengers lineup: Thor, Iron Man, Hulk, Ant-Man, Wasp'], 'curated'),
('Avengers', '4', 'Marvel', ARRAY['First Silver Age appearance of Captain America', 'Captain America joins the Avengers'], 'curated'),
('Avengers', '16', 'Marvel', ARRAY['New Avengers lineup'], 'curated'),
('Avengers', '57', 'Marvel', ARRAY['First appearance of Vision'], 'curated'),
('Avengers', '87', 'Marvel', ARRAY['Origin of Black Panther'], 'curated'),
('Avengers', '181', 'Marvel', ARRAY['First appearance of Scott Lang as Ant-Man'], 'curated'),
('Avengers', '195', 'Marvel', ARRAY['First cameo of Taskmaster'], 'curated'),
('Avengers', '196', 'Marvel', ARRAY['First full appearance of Taskmaster'], 'curated'),
('Avengers', '221', 'Marvel', ARRAY['Hawkeye becomes leader'], 'curated'),
('Avengers', '223', 'Marvel', ARRAY['Classic Hawkeye/Ant-Man'], 'curated'),
('Avengers', '500', 'Marvel', ARRAY['Avengers Disassembled'], 'curated'),
('West Coast Avengers', '45', 'Marvel', ARRAY['First White Vision'], 'curated'),
('New Avengers', '1', 'Marvel', ARRAY['New Avengers begins'], 'curated'),
('Young Avengers', '1', 'Marvel', ARRAY['First Young Avengers'], 'curated'),
('Dark Avengers', '1', 'Marvel', ARRAY['First Dark Avengers'], 'curated'),

-- MARVEL - IRON MAN / CAPTAIN AMERICA / THOR
('Tales of Suspense', '39', 'Marvel', ARRAY['First appearance of Iron Man'], 'curated'),
('Tales of Suspense', '52', 'Marvel', ARRAY['First appearance of Black Widow'], 'curated'),
('Tales of Suspense', '57', 'Marvel', ARRAY['First appearance of Hawkeye'], 'curated'),
('Tales to Astonish', '27', 'Marvel', ARRAY['First Ant-Man'], 'curated'),
('Iron Man', '1', 'Marvel', ARRAY['First Iron Man solo series'], 'curated'),
('Iron Man', '55', 'Marvel', ARRAY['First appearance of Thanos', 'First appearance of Drax the Destroyer'], 'curated'),
('Iron Man', '118', 'Marvel', ARRAY['First James Rhodes'], 'curated'),
('Iron Man', '128', 'Marvel', ARRAY['Demon in a Bottle storyline'], 'curated'),
('Iron Man', '282', 'Marvel', ARRAY['First War Machine armor'], 'curated'),
('Captain America', '1', 'Marvel', ARRAY['First appearance of Captain America (Golden Age)', 'First appearance of Bucky Barnes', 'First appearance of Red Skull'], 'curated'),
('Captain America', '100', 'Marvel', ARRAY['First Captain America solo (Silver Age)'], 'curated'),
('Captain America', '109', 'Marvel', ARRAY['Origin of Captain America retold'], 'curated'),
('Captain America', '117', 'Marvel', ARRAY['First appearance of Falcon'], 'curated'),
('Captain America', '176', 'Marvel', ARRAY['Captain America quits'], 'curated'),
('Captain America', '241', 'Marvel', ARRAY['Classic Punisher'], 'curated'),
('Captain America', '323', 'Marvel', ARRAY['First Super Patriot'], 'curated'),
('Captain America', '332', 'Marvel', ARRAY['Steve Rogers quits'], 'curated'),
('Captain America', '360', 'Marvel', ARRAY['First Crossbones'], 'curated'),
('Captain America', '383', 'Marvel', ARRAY['50th anniversary'], 'curated'),
('Captain America', '25', 'Marvel', ARRAY['Death of Captain America'], 'curated'),
('Journey Into Mystery', '83', 'Marvel', ARRAY['First appearance of Thor'], 'curated'),
('Thor', '165', 'Marvel', ARRAY['First full Him/Adam Warlock'], 'curated'),
('Thor', '337', 'Marvel', ARRAY['First appearance of Beta Ray Bill'], 'curated'),
('Thor', '411', 'Marvel', ARRAY['First New Warriors'], 'curated'),
('Thor', '1', 'Marvel', ARRAY['First appearance of Jane Foster as Thor'], 'curated'),
('Mighty Thor', '1', 'Marvel', ARRAY['Jane Foster Thor continues'], 'curated'),

-- MARVEL - FANTASTIC FOUR
('Fantastic Four', '1', 'Marvel', ARRAY['First appearance of the Fantastic Four', 'First appearance of Mole Man'], 'curated'),
('Fantastic Four', '5', 'Marvel', ARRAY['First appearance of Doctor Doom'], 'curated'),
('Fantastic Four', '12', 'Marvel', ARRAY['Hulk vs Thing'], 'curated'),
('Fantastic Four', '45', 'Marvel', ARRAY['First appearance of the Inhumans'], 'curated'),
('Fantastic Four', '46', 'Marvel', ARRAY['First full appearance of Black Bolt'], 'curated'),
('Fantastic Four', '48', 'Marvel', ARRAY['First appearance of Silver Surfer', 'First appearance of Galactus'], 'curated'),
('Fantastic Four', '49', 'Marvel', ARRAY['First full Galactus'], 'curated'),
('Fantastic Four', '52', 'Marvel', ARRAY['First appearance of Black Panther'], 'curated'),
('Fantastic Four', '67', 'Marvel', ARRAY['First Him (Adam Warlock)'], 'curated'),

-- MARVEL - GUARDIANS / COSMIC
('Marvel Super-Heroes', '18', 'Marvel', ARRAY['First appearance of the original Guardians of the Galaxy'], 'curated'),
('Marvel Super-Heroes', '13', 'Marvel', ARRAY['First Carol Danvers'], 'curated'),
('Marvel Preview', '4', 'Marvel', ARRAY['First appearance of Star-Lord'], 'curated'),
('Marvel Preview', '7', 'Marvel', ARRAY['First Rocket Raccoon full'], 'curated'),
('Guardians of the Galaxy', '1', 'Marvel', ARRAY['Modern GOTG (2008)'], 'curated'),
('Annihilation', '1', 'Marvel', ARRAY['Annihilation event'], 'curated'),
('Infinity Gauntlet', '1', 'Marvel', ARRAY['Infinity Gauntlet storyline begins', 'Thanos wields the Infinity Gauntlet'], 'curated'),
('Infinity Gauntlet', '2', 'Marvel', ARRAY['Infinity Gauntlet continues'], 'curated'),
('Silver Surfer', '1', 'Marvel', ARRAY['First Silver Surfer solo'], 'curated'),
('Silver Surfer', '3', 'Marvel', ARRAY['First Mephisto'], 'curated'),
('Silver Surfer', '4', 'Marvel', ARRAY['Classic Thor vs Surfer'], 'curated'),
('Silver Surfer', '44', 'Marvel', ARRAY['First appearance of the Infinity Gauntlet'], 'curated'),
('Warlock', '1', 'Marvel', ARRAY['Adam Warlock solo'], 'curated'),
('Thanos Quest', '1', 'Marvel', ARRAY['Thanos Quest begins'], 'curated'),
('Eternals', '1', 'Marvel', ARRAY['First Eternals'], 'curated'),
('Ms. Marvel', '1', 'Marvel', ARRAY['First Ms. Marvel'], 'curated'),
('Captain Marvel', '1', 'Marvel', ARRAY['First Mar-Vell solo'], 'curated'),

-- MARVEL - DAREDEVIL / STREET LEVEL
('Daredevil', '1', 'Marvel', ARRAY['First appearance of Daredevil', 'Origin of Daredevil'], 'curated'),
('Daredevil', '7', 'Marvel', ARRAY['First red costume'], 'curated'),
('Daredevil', '131', 'Marvel', ARRAY['First appearance of Bullseye'], 'curated'),
('Daredevil', '158', 'Marvel', ARRAY['Frank Miller begins'], 'curated'),
('Daredevil', '168', 'Marvel', ARRAY['First appearance of Elektra', 'Frank Millers Daredevil run begins'], 'curated'),
('Daredevil', '181', 'Marvel', ARRAY['Death of Elektra'], 'curated'),
('Daredevil', '227', 'Marvel', ARRAY['Born Again begins'], 'curated'),
('Hero for Hire', '1', 'Marvel', ARRAY['First appearance of Luke Cage'], 'curated'),
('Marvel Premiere', '15', 'Marvel', ARRAY['First appearance of Iron Fist'], 'curated'),
('Werewolf by Night', '32', 'Marvel', ARRAY['First appearance of Moon Knight'], 'curated'),
('Moon Knight', '1', 'Marvel', ARRAY['First Moon Knight solo'], 'curated'),

-- MARVEL - GHOST RIDER / BLADE / HORROR
('Marvel Spotlight', '5', 'Marvel', ARRAY['First appearance of Ghost Rider (Johnny Blaze)'], 'curated'),
('Ghost Rider', '1', 'Marvel', ARRAY['First Ghost Rider solo'], 'curated'),
('Tomb of Dracula', '10', 'Marvel', ARRAY['First appearance of Blade'], 'curated'),
('Strange Tales', '110', 'Marvel', ARRAY['First Doctor Strange'], 'curated'),
('Strange Tales', '135', 'Marvel', ARRAY['First Nick Fury, SHIELD'], 'curated'),
('Strange Tales', '169', 'Marvel', ARRAY['First Brother Voodoo'], 'curated'),
('Strange Tales', '178', 'Marvel', ARRAY['First Magus'], 'curated'),
('Marvel Two-in-One Annual', '2', 'Marvel', ARRAY['First Thanos death'], 'curated'),

-- MARVEL - MILES MORALES / SPIDER-VERSE
('Ultimate Fallout', '4', 'Marvel', ARRAY['First appearance of Miles Morales as Spider-Man'], 'curated'),
('Edge of Spider-Verse', '2', 'Marvel', ARRAY['First appearance of Spider-Gwen (Gwen Stacy as Spider-Woman)'], 'curated'),

-- MARVEL - VENOM
('Venom: Lethal Protector', '1', 'Marvel', ARRAY['First Venom solo series'], 'curated'),
('Venom', '1', 'Marvel', ARRAY['First issue of 2018 Venom series'], 'curated'),
('Venom', '3', 'Marvel', ARRAY['First appearance of Knull'], 'curated'),

-- MARVEL - SPIDER-MAN EXTENDED
('Spider-Verse', '1', 'Marvel', ARRAY['Spider-Verse event'], 'curated'),
('Spider-Man', '1', 'Marvel', ARRAY['McFarlane Spider-Man #1'], 'curated'),
('Spider-Gwen', '1', 'Marvel', ARRAY['Spider-Gwen solo'], 'curated'),
('Silk', '1', 'Marvel', ARRAY['First Silk solo'], 'curated'),
('Web of Spider-Man', '1', 'Marvel', ARRAY['First Web of Spider-Man'], 'curated'),
('Spectacular Spider-Man', '1', 'Marvel', ARRAY['First Spectacular Spider-Man'], 'curated'),
('Sensational Spider-Man', '1', 'Marvel', ARRAY['First Sensational Spider-Man'], 'curated'),
('Superior Spider-Man', '1', 'Marvel', ARRAY['First Superior Spider-Man'], 'curated'),
('Spider-Man 2099', '1', 'Marvel', ARRAY['First Spider-Man 2099'], 'curated'),
('What If', '105', 'Marvel', ARRAY['First Spider-Girl'], 'curated'),
('What If', '1', 'Marvel', ARRAY['First What If'], 'curated'),

-- MARVEL - EVENTS
('Contest of Champions', '1', 'Marvel', ARRAY['First limited series crossover'], 'curated'),
('House of M', '1', 'Marvel', ARRAY['House of M begins'], 'curated'),
('House of M', '7', 'Marvel', ARRAY['No More Mutants'], 'curated'),
('Civil War', '1', 'Marvel', ARRAY['Civil War begins'], 'curated'),
('Civil War', '7', 'Marvel', ARRAY['Death of Captain America tie-in'], 'curated'),
('Siege', '1', 'Marvel', ARRAY['Siege event'], 'curated'),
('Fear Itself', '1', 'Marvel', ARRAY['Fear Itself event'], 'curated'),
('Avengers vs X-Men', '1', 'Marvel', ARRAY['AvX event'], 'curated'),
('Age of Ultron', '1', 'Marvel', ARRAY['Age of Ultron event'], 'curated'),
('Original Sin', '1', 'Marvel', ARRAY['Original Sin event'], 'curated'),
('Secret Empire', '1', 'Marvel', ARRAY['Secret Empire event'], 'curated'),
('Secret Invasion', '1', 'Marvel', ARRAY['Secret Invasion event'], 'curated'),
('War of the Realms', '1', 'Marvel', ARRAY['War of the Realms event'], 'curated'),
('King in Black', '1', 'Marvel', ARRAY['King in Black event'], 'curated'),
('Absolute Carnage', '1', 'Marvel', ARRAY['Absolute Carnage event'], 'curated'),
('Extreme Carnage', '1', 'Marvel', ARRAY['Extreme Carnage event'], 'curated'),

-- MARVEL - BLACK PANTHER
('Black Panther', '1', 'Marvel', ARRAY['First Black Panther solo'], 'curated'),
('Black Panther', '7', 'Marvel', ARRAY['First Okoye'], 'curated'),
('Jungle Action', '6', 'Marvel', ARRAY['First Killmonger'], 'curated'),
('Shuri', '1', 'Marvel', ARRAY['First Shuri solo'], 'curated'),
('Killmonger', '1', 'Marvel', ARRAY['First Killmonger solo'], 'curated'),

-- MARVEL - MODERN SOLOS
('Vision', '1', 'Marvel', ARRAY['First Vision solo (King)'], 'curated'),
('Scarlet Witch', '1', 'Marvel', ARRAY['First Scarlet Witch solo'], 'curated'),
('Hawkeye', '1', 'Marvel', ARRAY['First Hawkeye solo (Fraction)'], 'curated'),
('Hawkeye', '2', 'Marvel', ARRAY['Pizza Dog'], 'curated'),
('She-Hulk', '1', 'Marvel', ARRAY['She-Hulk solo (2022)'], 'curated'),
('Loki', '1', 'Marvel', ARRAY['First Loki solo'], 'curated'),
('Runaways', '1', 'Marvel', ARRAY['First Runaways'], 'curated'),
('Champions', '1', 'Marvel', ARRAY['First Champions (2016)'], 'curated'),
('Squirrel Girl', '1', 'Marvel', ARRAY['First Unbeatable Squirrel Girl'], 'curated'),
('America', '1', 'Marvel', ARRAY['First America Chavez solo'], 'curated'),
('Power Pack', '1', 'Marvel', ARRAY['First Power Pack'], 'curated'),

-- DC - BATMAN
('Detective Comics', '27', 'DC', ARRAY['First appearance of Batman'], 'curated'),
('Detective Comics', '31', 'DC', ARRAY['Classic Batman cover'], 'curated'),
('Detective Comics', '38', 'DC', ARRAY['First appearance of Robin (Dick Grayson)'], 'curated'),
('Detective Comics', '140', 'DC', ARRAY['First appearance of the Riddler'], 'curated'),
('Detective Comics', '168', 'DC', ARRAY['Origin of Red Hood'], 'curated'),
('Detective Comics', '225', 'DC', ARRAY['First Martian Manhunter'], 'curated'),
('Detective Comics', '233', 'DC', ARRAY['First Batwoman'], 'curated'),
('Detective Comics', '359', 'DC', ARRAY['First appearance of Batgirl (Barbara Gordon)'], 'curated'),
('Detective Comics', '400', 'DC', ARRAY['First Man-Bat'], 'curated'),
('Detective Comics', '411', 'DC', ARRAY['First Talia al Ghul'], 'curated'),
('Detective Comics', '880', 'DC', ARRAY['Classic Jock Joker cover'], 'curated'),
('Detective Comics', '934', 'DC', ARRAY['Rebirth Detective Comics'], 'curated'),
('Batman', '1', 'DC', ARRAY['First appearance of Joker', 'First appearance of Catwoman'], 'curated'),
('Batman', '181', 'DC', ARRAY['First appearance of Poison Ivy'], 'curated'),
('Batman', '232', 'DC', ARRAY['First appearance of Ras al Ghul'], 'curated'),
('Batman', '251', 'DC', ARRAY['Classic Joker cover'], 'curated'),
('Batman', '357', 'DC', ARRAY['First appearance of Jason Todd'], 'curated'),
('Batman', '386', 'DC', ARRAY['First Black Mask'], 'curated'),
('Batman', '404', 'DC', ARRAY['Batman: Year One begins'], 'curated'),
('Batman', '423', 'DC', ARRAY['Classic McFarlane cover'], 'curated'),
('Batman', '426', 'DC', ARRAY['A Death in the Family storyline begins'], 'curated'),
('Batman', '427', 'DC', ARRAY['Death in the Family'], 'curated'),
('Batman', '428', 'DC', ARRAY['Death of Jason Todd'], 'curated'),
('Batman', '497', 'DC', ARRAY['Bane breaks Batmans back'], 'curated'),
('Batman', '567', 'DC', ARRAY['First Cassandra Cain Batgirl'], 'curated'),
('Batman', '608', 'DC', ARRAY['Hush storyline begins', 'Jim Lee art'], 'curated'),
('Batman', '655', 'DC', ARRAY['First appearance of Damian Wayne'], 'curated'),
('Batman Adventures', '12', 'DC', ARRAY['First comic book appearance of Harley Quinn'], 'curated'),
('Batman: The Killing Joke', '1', 'DC', ARRAY['The Killing Joke - Alan Moore/Brian Bolland', 'Barbara Gordon paralyzed'], 'curated'),
('Batman: Dark Knight Returns', '1', 'DC', ARRAY['The Dark Knight Returns begins - Frank Miller'], 'curated'),
('Harley Quinn', '1', 'DC', ARRAY['First Harley solo'], 'curated'),

-- DC - BAT-FAMILY
('Nightwing', '1', 'DC', ARRAY['First Nightwing solo'], 'curated'),
('Red Hood and the Outlaws', '1', 'DC', ARRAY['First Red Hood solo'], 'curated'),
('Batwoman', '1', 'DC', ARRAY['First Batwoman solo'], 'curated'),
('Batgirl', '1', 'DC', ARRAY['New 52 Batgirl'], 'curated'),
('Batgirl of Burnside', '35', 'DC', ARRAY['Burnside begins'], 'curated'),
('Robin', '1', 'DC', ARRAY['First Robin solo (Tim Drake)'], 'curated'),
('Batman and Robin', '1', 'DC', ARRAY['Morrison Batman and Robin'], 'curated'),
('Grayson', '1', 'DC', ARRAY['First Grayson spy series'], 'curated'),
('Gotham Central', '1', 'DC', ARRAY['First Gotham Central'], 'curated'),
('Birds of Prey', '1', 'DC', ARRAY['First Birds of Prey'], 'curated'),
('Catwoman', '1', 'DC', ARRAY['First Catwoman solo'], 'curated'),
('Poison Ivy', '1', 'DC', ARRAY['First Poison Ivy solo'], 'curated'),

-- DC - BATMAN EVENTS / MODERN
('Batman Who Laughs', '1', 'DC', ARRAY['First Batman Who Laughs solo'], 'curated'),
('Dark Nights: Metal', '1', 'DC', ARRAY['Metal event begins'], 'curated'),
('Dark Nights: Death Metal', '1', 'DC', ARRAY['Death Metal event'], 'curated'),
('Batman: White Knight', '1', 'DC', ARRAY['White Knight begins'], 'curated'),
('Three Jokers', '1', 'DC', ARRAY['Three Jokers begins'], 'curated'),
('DCeased', '1', 'DC', ARRAY['DCeased begins'], 'curated'),
('Injustice', '1', 'DC', ARRAY['First Injustice'], 'curated'),
('Batman/Fortnite', '1', 'DC', ARRAY['Batman Fortnite crossover'], 'curated'),

-- DC - SUPERMAN
('Action Comics', '1', 'DC', ARRAY['First appearance of Superman', 'Most valuable comic book in existence'], 'curated'),
('Action Comics', '242', 'DC', ARRAY['First Brainiac'], 'curated'),
('Action Comics', '252', 'DC', ARRAY['First appearance of Supergirl'], 'curated'),
('Action Comics', '521', 'DC', ARRAY['First Vixen'], 'curated'),
('Superman', '1', 'DC', ARRAY['First Superman solo (Golden Age)'], 'curated'),
('Superman', '75', 'DC', ARRAY['Death of Superman'], 'curated'),
('Superman', '233', 'DC', ARRAY['Classic Kryptonite No More'], 'curated'),
('Supermans Pal Jimmy Olsen', '134', 'DC', ARRAY['First appearance of Darkseid (cameo)'], 'curated'),
('Forever People', '1', 'DC', ARRAY['First full appearance of Darkseid'], 'curated'),
('Adventure Comics', '247', 'DC', ARRAY['First Legion of Super-Heroes'], 'curated'),
('Superboy', '68', 'DC', ARRAY['First Bizarro'], 'curated'),
('Supergirl', '1', 'DC', ARRAY['First Supergirl solo (modern)'], 'curated'),
('Superboy', '1', 'DC', ARRAY['First Superboy solo (Kon-El)'], 'curated'),

-- DC - NEW GODS / FOURTH WORLD
('New Gods', '1', 'DC', ARRAY['First Orion, New Gods'], 'curated'),
('New Gods', '7', 'DC', ARRAY['First Steppenwolf'], 'curated'),
('Mister Miracle', '1', 'DC', ARRAY['First Mister Miracle'], 'curated'),

-- DC - WONDER WOMAN
('All Star Comics', '8', 'DC', ARRAY['First appearance of Wonder Woman'], 'curated'),
('Sensation Comics', '1', 'DC', ARRAY['Wonder Woman origin'], 'curated'),
('Wonder Woman', '1', 'DC', ARRAY['First Wonder Woman solo comic'], 'curated'),
('Wonder Woman', '98', 'DC', ARRAY['First Silver Age Wonder Woman'], 'curated'),
('Wonder Woman', '178', 'DC', ARRAY['New Wonder Woman begins'], 'curated'),
('Wonder Woman', '329', 'DC', ARRAY['Last pre-Crisis'], 'curated'),

-- DC - FLASH / GREEN LANTERN
('Showcase', '4', 'DC', ARRAY['First appearance of Barry Allen Flash', 'Beginning of the Silver Age of Comics'], 'curated'),
('Showcase', '22', 'DC', ARRAY['First appearance of Hal Jordan Green Lantern'], 'curated'),
('Showcase', '34', 'DC', ARRAY['First Silver Age Atom'], 'curated'),
('Flash', '1', 'DC', ARRAY['First Flash solo (Silver Age)'], 'curated'),
('Flash', '105', 'DC', ARRAY['First Silver Age Flash'], 'curated'),
('Flash', '110', 'DC', ARRAY['First Kid Flash'], 'curated'),
('Flash', '123', 'DC', ARRAY['Flash of Two Worlds - first Silver Age/Golden Age crossover', 'Introduction of the multiverse concept'], 'curated'),
('Flash', '139', 'DC', ARRAY['First appearance of Reverse Flash (Professor Zoom)'], 'curated'),
('Green Lantern', '1', 'DC', ARRAY['First Green Lantern solo (Silver Age)'], 'curated'),
('Green Lantern', '7', 'DC', ARRAY['First appearance of Sinestro'], 'curated'),
('Green Lantern', '59', 'DC', ARRAY['First Guy Gardner'], 'curated'),
('Green Lantern', '76', 'DC', ARRAY['Green Lantern/Green Arrow begins - Dennis ONeil/Neal Adams'], 'curated'),
('Green Lantern', '87', 'DC', ARRAY['First appearance of John Stewart'], 'curated'),
('Green Lantern', '122', 'DC', ARRAY['Guy Gardner backup begins'], 'curated'),
('Green Lantern', '188', 'DC', ARRAY['First Star Sapphire modern'], 'curated'),
('Green Lantern', '195', 'DC', ARRAY['Guy Gardner gets ring'], 'curated'),
('Green Lantern', '50', 'DC', ARRAY['Emerald Twilight (1994)'], 'curated'),
('Green Lantern Corps', '201', 'DC', ARRAY['Kilowog spotlight'], 'curated'),
('Green Lantern: Rebirth', '1', 'DC', ARRAY['Hal Jordan returns'], 'curated'),
('Green Arrow', '1', 'DC', ARRAY['First Green Arrow solo'], 'curated'),
('Aquaman', '35', 'DC', ARRAY['First Black Manta'], 'curated'),
('Black Canary', '1', 'DC', ARRAY['First Black Canary solo'], 'curated'),

-- DC - JUSTICE LEAGUE / TEEN TITANS
('Brave and the Bold', '28', 'DC', ARRAY['First appearance of the Justice League of America'], 'curated'),
('Justice League', '1', 'DC', ARRAY['Justice League International'], 'curated'),
('Justice League of America', '1', 'DC', ARRAY['First JLA solo'], 'curated'),
('Justice League of America', '21', 'DC', ARRAY['First Silver Age JSA'], 'curated'),
('Justice League of America', '29', 'DC', ARRAY['First Starman'], 'curated'),
('New Teen Titans', '1', 'DC', ARRAY['First appearance of the New Teen Titans team'], 'curated'),
('New Teen Titans', '2', 'DC', ARRAY['First appearance of Deathstroke'], 'curated'),
('DC Comics Presents', '26', 'DC', ARRAY['First appearance of Cyborg', 'First appearance of Raven', 'First appearance of Starfire'], 'curated'),
('Tales of the Teen Titans', '44', 'DC', ARRAY['First appearance of Nightwing costume'], 'curated'),
('Teen Titans', '12', 'DC', ARRAY['First Wally West as Kid Flash'], 'curated'),
('Titans', '1', 'DC', ARRAY['Titans Rebirth'], 'curated'),
('Deathstroke', '1', 'DC', ARRAY['First Deathstroke solo'], 'curated'),
('Blue Beetle', '1', 'DC', ARRAY['First Jaime Reyes solo'], 'curated'),
('Doom Patrol', '99', 'DC', ARRAY['First Beast Boy'], 'curated'),
('Suicide Squad', '1', 'DC', ARRAY['First modern Suicide Squad'], 'curated'),

-- DC - CRISIS / EVENTS
('Crisis on Infinite Earths', '1', 'DC', ARRAY['Crisis on Infinite Earths begins'], 'curated'),
('Crisis on Infinite Earths', '7', 'DC', ARRAY['Death of Supergirl'], 'curated'),
('Crisis on Infinite Earths', '8', 'DC', ARRAY['Death of Barry Allen Flash'], 'curated'),
('Infinite Crisis', '1', 'DC', ARRAY['Infinite Crisis begins'], 'curated'),
('Final Crisis', '1', 'DC', ARRAY['Final Crisis begins'], 'curated'),
('Identity Crisis', '1', 'DC', ARRAY['Identity Crisis begins'], 'curated'),
('52', '1', 'DC', ARRAY['52 weekly series'], 'curated'),
('Countdown', '51', 'DC', ARRAY['Countdown begins'], 'curated'),
('Doomsday Clock', '1', 'DC', ARRAY['Doomsday Clock begins'], 'curated'),
('Flashpoint', '1', 'DC', ARRAY['Flashpoint event begins', 'Leads to New 52 reboot'], 'curated'),
('Dark Nights: Metal', '2', 'DC', ARRAY['First appearance of the Batman Who Laughs'], 'curated'),
('DC Special Series', '27', 'DC', ARRAY['First Batman/Superman vs Hulk'], 'curated'),
('Marvel vs DC', '1', 'DC', ARRAY['Marvel vs DC'], 'curated'),

-- DC - VERTIGO / OTHER
('Swamp Thing', '37', 'DC', ARRAY['First appearance of John Constantine'], 'curated'),
('Hellblazer', '1', 'DC', ARRAY['First Constantine solo'], 'curated'),
('Sandman', '1', 'DC', ARRAY['First appearance of Dream/Morpheus - Neil Gaiman'], 'curated'),
('Sandman', '8', 'DC', ARRAY['First Death'], 'curated'),
('Watchmen', '1', 'DC', ARRAY['Watchmen begins - Alan Moore/Dave Gibbons'], 'curated'),
('V for Vendetta', '1', 'DC', ARRAY['First V for Vendetta'], 'curated'),
('Preacher', '1', 'DC', ARRAY['First Preacher'], 'curated'),
('Y: The Last Man', '1', 'DC', ARRAY['First Y: The Last Man'], 'curated'),
('Fables', '1', 'DC', ARRAY['First Fables'], 'curated'),
('Transmetropolitan', '1', 'DC', ARRAY['First Transmetropolitan'], 'curated'),
('100 Bullets', '1', 'DC', ARRAY['First 100 Bullets'], 'curated'),
('Sweet Tooth', '1', 'DC', ARRAY['First Sweet Tooth'], 'curated'),
('The Nice House on the Lake', '1', 'DC', ARRAY['First Nice House on the Lake'], 'curated'),
('Human Target', '1', 'DC', ARRAY['Human Target (King)'], 'curated'),
('Strange Adventures', '1', 'DC', ARRAY['Strange Adventures (King)'], 'curated'),
('Omega Men', '1', 'DC', ARRAY['Omega Men (King)'], 'curated'),
('Sheriff of Babylon', '1', 'DC', ARRAY['First Sheriff of Babylon'], 'curated'),

-- IMAGE - SPAWN
('Spawn', '1', 'Image', ARRAY['First appearance of Spawn', 'Todd McFarlane creator-owned'], 'curated'),
('Spawn', '9', 'Image', ARRAY['First Angela'], 'curated'),
('Spawn', '174', 'Image', ARRAY['First She-Spawn'], 'curated'),

-- IMAGE - WALKING DEAD / KIRKMAN
('Walking Dead', '1', 'Image', ARRAY['First appearance of Rick Grimes', 'Walking Dead series begins'], 'curated'),
('Walking Dead', '19', 'Image', ARRAY['First appearance of Michonne'], 'curated'),
('Walking Dead', '27', 'Image', ARRAY['First Governor'], 'curated'),
('Walking Dead', '92', 'Image', ARRAY['First Jesus'], 'curated'),
('Walking Dead', '100', 'Image', ARRAY['First appearance of Negan'], 'curated'),
('Invincible', '1', 'Image', ARRAY['First appearance of Invincible - Robert Kirkman'], 'curated'),
('Outcast', '1', 'Image', ARRAY['First Outcast'], 'curated'),
('Oblivion Song', '1', 'Image', ARRAY['First Oblivion Song'], 'curated'),
('Fire Power', '1', 'Image', ARRAY['First Fire Power'], 'curated'),

-- IMAGE - SAGA / BKV
('Saga', '1', 'Image', ARRAY['Saga series begins - Brian K. Vaughan'], 'curated'),
('Paper Girls', '1', 'Image', ARRAY['First Paper Girls'], 'curated'),

-- IMAGE - MODERN HITS
('Something is Killing the Children', '1', 'Image', ARRAY['First SIKTC'], 'curated'),
('House of Slaughter', '1', 'Image', ARRAY['First House of Slaughter'], 'curated'),
('Department of Truth', '1', 'Image', ARRAY['First Department of Truth'], 'curated'),
('Nocterra', '1', 'Image', ARRAY['First Nocterra'], 'curated'),
('Geiger', '1', 'Image', ARRAY['First Geiger'], 'curated'),
('Ice Cream Man', '1', 'Image', ARRAY['First Ice Cream Man'], 'curated'),
('Gideon Falls', '1', 'Image', ARRAY['First Gideon Falls'], 'curated'),
('Bitter Root', '1', 'Image', ARRAY['First Bitter Root'], 'curated'),
('Undiscovered Country', '1', 'Image', ARRAY['First Undiscovered Country'], 'curated'),
('Crossover', '1', 'Image', ARRAY['First Crossover'], 'curated'),
('East of West', '1', 'Image', ARRAY['First East of West'], 'curated'),
('Deadly Class', '1', 'Image', ARRAY['First Deadly Class'], 'curated'),
('Descender', '1', 'Image', ARRAY['First Descender'], 'curated'),
('Low', '1', 'Image', ARRAY['First Low'], 'curated'),
('Black Science', '1', 'Image', ARRAY['First Black Science'], 'curated'),
('Chew', '1', 'Image', ARRAY['First Chew'], 'curated'),

-- INDEPENDENT - CLASSIC
('Teenage Mutant Ninja Turtles', '1', 'Independent', ARRAY['First appearance of the Teenage Mutant Ninja Turtles'], 'curated'),
('Bone', '1', 'Independent', ARRAY['First Bone'], 'curated'),
('Usagi Yojimbo', '1', 'Independent', ARRAY['First Usagi Yojimbo'], 'curated'),
('Hellboy', '1', 'Dark Horse', ARRAY['First Hellboy'], 'curated'),
('Sin City', '1', 'Dark Horse', ARRAY['First Sin City'], 'curated'),
('300', '1', 'Dark Horse', ARRAY['First 300'], 'curated'),
('Maus', '1', 'Independent', ARRAY['First Maus'], 'curated'),
('Locke & Key', '1', 'IDW', ARRAY['First Locke & Key'], 'curated')

ON CONFLICT (title_normalized, issue_number) DO NOTHING;
